"""
Configuration module
"""

from .config import MODEL_CONFIG, IMAGE_CONFIG, PROCESSING_CONFIG, PATHS, SUPPORTED_FORMATS

__all__ = ["MODEL_CONFIG", "IMAGE_CONFIG", "PROCESSING_CONFIG", "PATHS", "SUPPORTED_FORMATS"]
